function SetPath(hObj,~,f,filesToBrowse)
%----------------------------------------------------------------------
%----------------------------------------------------------------------
%---             --- Thomas Gautrais                                ---
%---    Author   --- thomas.gautrais@univ-st-etienne.fr             ---
%---             --- Laboratoire Hubert Curien (UMR 5516)           ---
%----------------------------------------------------------------------
%---             --- Callback of the 'Browse ...' push buttons in   ---
%--- Description --- the figures generated by the DetectionGui.m    ---
%---             --- and TrackingGui.m.                             ---
%----------------------------------------------------------------------
%---   Version   ---  2019-03-01:                                   ---
%---   History   ---       First version                            ---
%----------------------------------------------------------------------
%----------------------------------------------------------------------
%
% Copyright (c) 2019, Hugo Lafaye de Micheaux, Thomas Gautrais, Université
% Jean Monnet, CNRS, Irstea
% All rights reserved.
%
% This source code is part of the BeadTracking package
% <https://github.com/hugolafaye/BeadTracking> and it is licensed under the
% BSD-style license found in the LICENSE file in the root directory of this
% source tree.

s=guidata(f);

idx=find(s.path.hPush==hObj);
seqDirIdx=It2DefStructFieldIdx(s.path,idx);

pathSeqDirStr=get(s.path.hText(strcmp(s.path.mapKeys,...
    s.path.fieldNames.PATH_SEQUENCE_DIR)),'String');

% sequence path
if seqDirIdx==Field2Idx(s.path.fieldNames.PATH_SEQUENCE_DIR,...
        s.path.defaultStructFields(:,1))
    if exist(get(s.path.hText(idx),'String'),'dir')
        startPath=[get(s.path.hText(idx),'String'),filesep,'..'];
    else
        startPath=pwd();
    end
    name=uigetdir(startPath,'Select the path of the sequence of images');
    if name
        [dirname,pathname]=fileparts(name);
        path=fullfile(dirname,pathname);
        set(s.path.hText(idx),'String',path);
    end
    
% result path
elseif seqDirIdx==Field2Idx(s.path.fieldNames.PATH_RESULTS_DIR,...
        s.path.defaultStructFields(:,1))
    oldCurrentFolder=pwd;
    newCdPath=pathSeqDirStr;
    if exist(newCdPath,'dir'), cd(newCdPath); end
    name=uigetdir(get(s.path.hText(idx),'String'),...
        'Select the path of the results');
    if name
        [dirname,pathname]=fileparts(name);
        path=fullfile(dirname,pathname);
        set(s.path.hText(idx),'String',path);
    end
    cd(oldCurrentFolder);

% txt, tif and mat file path
elseif max(seqDirIdx==Field2Idx(filesToBrowse,s.path.defaultStructFields(:,1)))
    oldCurrentFolder=pwd;
    newCdPath=pathSeqDirStr;
    if exist(newCdPath,'dir'), cd(newCdPath); end
    [file,dirname]=uigetfile(s.path.filterCells{seqDirIdx});
    if dirname(end)==filesep, dirname=dirname(1:end-1); end
    if file
        if isempty(strfind(dirname,pathSeqDirStr))
            msgbox(['You must select a file which is in the sequence',...
                'path or subfolders'],'File is not in the Sequence Path','warn');
        else
            set(s.path.hText(idx),'String',file);
        end
        cd(oldCurrentFolder);
    end
    
end

guidata(f,s);

end