function [outStruct,run,close_fig] = Submit(hObj,f)
%----------------------------------------------------------------------
%----------------------------------------------------------------------
%---             --- Thomas Gautrais                                ---
%---    Author   --- thomas.gautrais@univ-st-etienne.fr             ---
%---             --- Laboratoire Hubert Curien (UMR 5516)           ---
%----------------------------------------------------------------------
%---             --- Function called by SubmitDetection and         ---
%--- Description --- SubmitTracking callabcks in the figures        ---
%---             --- generated by the DetectionGui.m and            ---
%---             --- TrackingGui.m                                  ---
%----------------------------------------------------------------------
%---   Version   --- 2019-03-01:                                    ---
%---   History   ---   This function is the callback of 'RUN' and   ---
%---             ---   'CANCEL' push buttons and close figure       ---
%---             ---   button for both DetectionGui and TrackingGui ---
%---             --- 2019-03-20:                                    ---     
%---             ---   This function isn't a real callback anymore, ---
%---             ---   but a function, which is called from the     ---
%---             ---   SubmitDetection and SubmitTracking callbacks ---   
%---             ---   to perform the common tasks                  ---   
%----------------------------------------------------------------------
%----------------------------------------------------------------------
%
% Copyright (c) 2019, Hugo Lafaye de Micheaux, Thomas Gautrais, Université
% Jean Monnet, CNRS, Irstea
% All rights reserved.
%
% This source code is part of the BeadTracking package
% <https://github.com/hugolafaye/BeadTracking> and it is licensed under the
% BSD-style license found in the LICENSE file in the root directory of this
% source tree.

s=guidata(f);

close_fig=0;
if     hObj==s.submit.run,               run=true;
elseif hObj==s.submit.cancel || hObj==f, run=false;
end
outStruct=[];

if run
    for m=1:s.real.count
        rawVal=get(s.real.hEdit(m),'String');
        if isnan(str2double(rawVal))
            set(s.submit.info,'String',['Value of the field "',...
                s.real.mapKeys{m},'" must be a number.']);
            return;
        end
    end
    set(s.submit.info,'String','');
end

for m=1:s.path.count
    if     max(It2DefStructFieldIdx(s.path,m)==s.path.editIdx)
        outStruct.(s.path.mapKeys{m})=get(s.path.hEdit(m),'String');
    elseif max(It2DefStructFieldIdx(s.path,m)==s.path.browseIdx)
        outStruct.(s.path.mapKeys{m})=get(s.path.hText(m),'String');
    end
end

for m=1:s.bool.count
    outStruct.(s.bool.mapKeys{m})=logical(get(s.bool.hCheck(m),'Value'));
end

for m=1:s.real.count
    outStruct.(s.real.mapKeys{m})=str2double(get(s.real.hEdit(m),'String'));
end

close_fig=1;

end