function SubmitTracking(hObj,~,f)
%----------------------------------------------------------------------
%----------------------------------------------------------------------
%---             --- Thomas Gautrais                                ---
%---    Author   --- thomas.gautrais@univ-st-etienne.fr             ---
%---             --- Laboratoire Hubert Curien (UMR 5516)           ---
%----------------------------------------------------------------------
%---             --- Callback of the 'RUN' and 'CANCEL' push        ---
%--- Description --- buttons and close figure button in the figure  ---
%---             --- generated by the TrackingGui.m.                ---
%----------------------------------------------------------------------
%---   Version   ---  2019-03-20:                                   ---
%---   History   ---       First version of the file                ---
%----------------------------------------------------------------------
%----------------------------------------------------------------------
%
% Copyright (c) 2019, Hugo Lafaye de Micheaux, Thomas Gautrais, Université
% Jean Monnet, CNRS, Irstea
% All rights reserved.
%
% This source code is part of the BeadTracking package
% <https://github.com/hugolafaye/BeadTracking> and it is licensed under the
% BSD-style license found in the LICENSE file in the root directory of this
% source tree.

s=guidata(f);

[outStruct,run,closef]=Submit(hObj,f);

if closef
    assignin('caller','outStruct',outStruct);
    assignin('caller','run',run);
    set(0,'CurrentFigure',f);
    closereq;
    pause(0.01);
end

end