function UpdateEnableStatesDetection(hObj, ~, f)
%----------------------------------------------------------------------
%----------------------------------------------------------------------
%---             --- Thomas Gautrais                                ---
%---    Author   --- thomas.gautrais@univ-st-etienne.fr             ---
%---             --- Laboratoire Hubert Curien (UMR 5516)           ---
%----------------------------------------------------------------------
%--- Description --- Callback of the checkbox buttons in the        ---
%---             --- the figure generated by the DetectionGui.m.    ---
%----------------------------------------------------------------------
%---   Version   --- 2019-03-01:                                    ---
%---   History   ---   First version                                ---
%---             --- 2019-03-20:                                    ---
%---             ---   Adding a new 'elseif' block corresponding to --- 
%---             ---   the compute detector confidence of           ---
%---             ---   transparent beads.                           ---
%----------------------------------------------------------------------
%----------------------------------------------------------------------
%
% Copyright (c) 2019, Hugo Lafaye de Micheaux, Thomas Gautrais, Université
% Jean Monnet, CNRS, Irstea
% All rights reserved.
%
% This source code is part of the BeadTracking package
% <https://github.com/hugolafaye/BeadTracking> and it is licensed under the
% BSD-style license found in the LICENSE file in the root directory of this
% source tree.

s=guidata(f);

idx=find(s.bool.hCheck==hObj);
seqDirIdx=It2DefStructFieldIdx(s.bool,idx);

isChecked=get(hObj,'Value');

% remove base
if seqDirIdx==Field2Idx(s.bool.fieldNames.BOOL_REMOVE_BASE,...
        s.bool.defaultStructFields(:,1))
    pathIdx=strcmp(s.path.mapKeys,s.path.fieldNames.PATH_MASK_FILE);
    obj=[s.path.hText(pathIdx),s.path.hPush(pathIdx)];
    if isChecked, set(obj,'Enable','on');
    else          set(obj,'Enable','off');
    end
    
% detect black beads
elseif seqDirIdx==Field2Idx(s.bool.fieldNames.BOOL_BLACK,...
        s.bool.defaultStructFields(:,1))
    realIdx=strcmp(s.real.mapKeys,s.real.fieldNames.REAL_BLACK_TH);
    obj=[s.real.hText(realIdx),s.real.hEdit(realIdx)];
    if isChecked, set(obj,'Enable','on');
    else          set(obj,'Enable','off');
    end
    
% detect transparent beads
elseif seqDirIdx==Field2Idx(s.bool.fieldNames.BOOL_TRANS,...
        s.bool.defaultStructFields(:,1))
    pathIdx=strcmp(s.path.mapKeys,s.path.fieldNames.PATH_TRANS_FILE);
    realIdx=strcmp(s.real.mapKeys,s.real.fieldNames.REAL_TRANS_TH) | ...
            strcmp(s.real.mapKeys,s.real.fieldNames.REAL_TRANS_HMAX) | ...
            strcmp(s.real.mapKeys,s.real.fieldNames.REAL_TRANS_RAD_FILT) | ...
            strcmp(s.real.mapKeys,s.real.fieldNames.REAL_TRANS_NB_FILT);
    obj=[s.path.hText(pathIdx),s.path.hPush(pathIdx),...
         s.real.hText(realIdx),s.real.hEdit(realIdx)];
     
    h_trans_conf = s.bool.hCheck(strcmp(s.bool.mapKeys,...
        s.bool.fieldNames.BOOL_TRANS_CONF));
    if isChecked
        set(obj,'Enable','on');
        set(h_trans_conf, 'Enable', 'on')
        if get(h_trans_conf, 'Value')
            set(h_trans_conf, 'Value', 0)
            UpdateEnableStatesDetection(h_trans_conf, [], f)
        end
    else
        set(obj,'Enable','off');
        set(h_trans_conf, 'Enable', 'off')
        if get(h_trans_conf, 'Value')
            set(h_trans_conf, 'Value', 0)
            UpdateEnableStatesDetection(h_trans_conf, [], f)
        end
    end
    
    
% compute detector confidence of transparent beads
elseif seqDirIdx==Field2Idx(s.bool.fieldNames.BOOL_TRANS_CONF,...
        s.bool.defaultStructFields(:,1))   
    realIdx=strcmp(s.real.mapKeys,s.real.fieldNames.REAL_TRANS_CONF_TH);
    obj=[s.real.hText(realIdx),s.real.hEdit(realIdx)];
    if isChecked, set(obj,'Enable','on');
    else          set(obj,'Enable','off');
    end    
    
% detect water lines
elseif seqDirIdx==Field2Idx(s.bool.fieldNames.BOOL_WATER_LINE,...
        s.bool.defaultStructFields(:,1))
    realIdx=strcmp(s.real.mapKeys,s.real.fieldNames.REAL_WATER_LINE_TH); 
    obj=[s.real.hText(realIdx),s.real.hEdit(realIdx)];
    if isChecked, set(obj,'Enable','on');
    else          set(obj,'Enable','off');
    end
end

end