function UpdateEnableStatesTracking(hObj,~,f)
%----------------------------------------------------------------------
%----------------------------------------------------------------------
%---             --- Thomas Gautrais                                ---
%---    Author   --- thomas.gautrais@univ-st-etienne.fr             ---
%---             --- Laboratoire Hubert Curien (UMR 5516)           ---
%----------------------------------------------------------------------
%--- Description --- Callback of the checkbox buttons in the        ---
%---             --- the figure generated by the TrackingGui.m.     ---
%----------------------------------------------------------------------
%---   Version   ---  2019-03-01:                                   ---
%---   History   ---       First version                            ---
%----------------------------------------------------------------------
%----------------------------------------------------------------------
%
% Copyright (c) 2019, Hugo Lafaye de Micheaux, Thomas Gautrais, Université
% Jean Monnet, CNRS, Irstea
% All rights reserved.
%
% This source code is part of the BeadTracking package
% <https://github.com/hugolafaye/BeadTracking> and it is licensed under the
% BSD-style license found in the LICENSE file in the root directory of this
% source tree.

s=guidata(f);

idx=find(s.bool.hCheck==hObj);
seqDirIdx=It2DefStructFieldIdx(s.bool,idx);

isChecked=get(hObj,'Value');

if seqDirIdx==Field2Idx(s.bool.fieldNames.BOOL_MOTION_STATES,...
        s.bool.defaultStructFields(:,1))
    % motion states
    realIdx=strcmp(s.real.mapKeys,s.real.fieldNames.REAL_MS_VELO_REST) | ...
            strcmp(s.real.mapKeys,s.real.fieldNames.REAL_MS_VELO_SALT) | ...
            strcmp(s.real.mapKeys,s.real.fieldNames.REAL_MS_FACT_NEIGH);
    obj=[s.real.hText(realIdx),s.real.hEdit(realIdx)];
    if isChecked, set(obj,'Enable','on');
    else          set(obj,'Enable','off');
    end
end

end